// RedRight Onboarding Screens — Tattoo v2
window.RR_ONBOARDING_VERTICAL_KEY = "tattoo_v2";

const get = (state, key) => (state ? state[key] : undefined);

const FLOWS = {
  shop: [
    {
      id: "SHOP_S0_WELCOME",
      type: "single",
      title: "",
      quote: "You can change anything later just by texting Isla.",
      question: "This takes a few minutes.",
      key: "shop.welcome_ack",
      options: [{ label: "Continue", value: "ok", primary: true }],
      next: "SHOP_S1_IDENTITY",
    },
    {
      id: "SHOP_S1_IDENTITY",
      type: "form",
      title: "Shop",
      quote: "Quiet basics. No back-and-forth later.",
      question: "What should Isla call your shop?",
      fields: [
        { id: "shop.name", label: "Shop name", kind: "text", required: true, max_length: 60 },
        { id: "shop.timezone", label: "Timezone", kind: "timezone", required: true },
      ],
      next: "SHOP_S2_BRANDING",
    },
    {
      id: "SHOP_S2_BRANDING",
      type: "upload",
      title: "Branding",
      quote: "This is how clients recognize your shop.",
      question: "Upload your logo.",
      upload: { field_id: "shop.logo.asset_id", required: true },
      next: "SHOP_S3_HOURS",
    },
    {
      id: "SHOP_S3_HOURS",
      type: "hours",
      title: "Hours",
      quote: "Set once. Isla follows it.",
      question: "Set your shop hours.",
      next: "SHOP_S3B_ROSTER_BUILD",
    },
    {
      id: "SHOP_S3B_ROSTER_BUILD",
      type: "roster_build",
      title: "Team",
      quote: "So Isla always knows who’s who.",
      question: "Add your team.",
      next: "SHOP_S4_CONTACT_LINE",
    },
    {
      id: "SHOP_S4_CONTACT_LINE",
      type: "phone",
      title: "Shop line",
      quote: "This is the number clients will reach.",
      question: "What number should clients call?",
      key: "shop.isla_line.phone",
      next: "SHOP_S5_OPS_HELP_PICK",
    },
    {
      id: "SHOP_S5_OPS_HELP_PICK",
      type: "roster",
      title: "Second set of eyes",
      quote: "Quiet backup. Nothing dramatic.",
      question:
        "If Isla needs a quick decision and can’t reach the right person,\nwho can she quietly loop in to help keep things moving?",
      key: "shop.ops_help.primary_person_id",
      source: "roster",
      next: "SHOP_S7_AFTER_HOURS",
    },
    {
      id: "SHOP_S7_AFTER_HOURS",
      type: "single",
      title: "After hours",
      quote: "Clients are acknowledged — without creating urgency.",
      question: "After hours, should Isla…",
      key: "shop.after_hours.policy",
      options: [
        { label: "Handle it, but hold until business hours", value: "hold_to_hours" },
        { label: "Reach out anytime", value: "anytime" },
        { label: "Emergency only", value: "emergency_only" },
      ],
      next: "SHOP_S6_OWNER_PROVIDER_CHECK_LAST",
    },
    {
      id: "SHOP_S6_OWNER_PROVIDER_CHECK_LAST",
      type: "single",
      title: "Owner",
      quote: "This decides what I configure next.",
      question: "Do you tattoo clients yourself?",
      key: "owner.is_provider",
      options: [
        { label: "Yes", value: true, primary: true },
        { label: "No", value: false },
      ],
      next: (state) => (get(state, "owner.is_provider") ? "ARTIST_A0_WELCOME" : "SHOP_S8_QUIET_EXIT"),
    },
    {
      id: "SHOP_S8_QUIET_EXIT",
      type: "end",
      title: "",
      quote: "",
      question: "Shop preferences saved.\nThank you.",
    },
  ],

  artist: [
    {
      id: "ARTIST_A0_WELCOME",
      type: "single",
      title: "",
      quote: "Built to protect your time and keep your books full — without extra work.",
      question: "Artist preferences.\nA few quick choices.",
      key: "artist.welcome_ack",
      options: [{ label: "Continue", value: "ok", primary: true }],
      next: "ARTIST_A1_IN_SESSION",
    },
    {
      id: "ARTIST_A1_IN_SESSION",
      type: "single",
      title: "When you’re tattooing",
      quote: "I’ll work around your flow — not interrupt it.",
      question: "If someone reaches out while you’re in session…",
      key: "in_session.policy",
      options: [
        { label: "Try me first (a quick approve is fine)", value: "try_first" },
        { label: "Hold everything until I’m free", value: "hold" },
        { label: "Text me once only if it’s urgent", value: "text_once_urgent" },
      ],
      next: "ARTIST_A2_AFTER_HOURS",
    },
    {
      id: "ARTIST_A2_AFTER_HOURS",
      type: "single",
      title: "After hours",
      quote: "You decide when I can reach you — I’ll handle the rest.",
      question: "After hours, should Isla…",
      key: "after_hours.policy",
      options: [
        { label: "Handle it, but hold until business hours", value: "hold_to_hours" },
        { label: "Reach out to me anytime", value: "anytime" },
        { label: "Emergency only", value: "emergency_only" },
      ],
      next: "ARTIST_A3_PLACEMENTS_DONT_DO",
    },
    {
      id: "ARTIST_A3_PLACEMENTS_DONT_DO",
      type: "multi",
      title: "Placements",
      quote: "This prevents awkward situations before they start.",
      question: "Which placements do you NOT tattoo?",
      key: "tattoo.placements.do_not",
      options: [
        { label: "Face", value: "face" },
        { label: "Neck", value: "neck" },
        { label: "Hands", value: "hands" },
        { label: "Feet", value: "feet" },
        { label: "Breasts / nipples", value: "breasts" },
        { label: "Genitals", value: "genitals" },
        { label: "Butt / groin-adjacent", value: "butt_groin" },
        { label: "Inner thigh", value: "inner_thigh" },
      ],
      next: "ARTIST_A4_AGE_POLICY",
    },
    {
      id: "ARTIST_A4_AGE_POLICY",
      type: "single",
      title: "Age policy",
      quote: "Clear boundaries. No awkward conversations.",
      question: "What’s your policy for clients under 18?",
      key: "tattoo.age_policy",
      options: [
        { label: "18+ only", value: "18_plus", primary: true },
        { label: "16–17 with parent/guardian consent", value: "16_17_consent" },
        { label: "Case-by-case (always route for approval)", value: "case_by_case" },
      ],
      next: "ARTIST_A5_COVERAGE_ROUTING",
    },
    {
      id: "ARTIST_A5_COVERAGE_ROUTING",
      type: "roster",
      title: "Second set of eyes",
      quote: "If Isla can’t reach you after a couple attempts,\nwho should she quietly loop in to help keep things moving?",
      question: "Who can help keep things moving?",
      key: "escalation.target_person_id",
      source: "roster",
      next: "ARTIST_A6_CAREWATCH",
    },
    {
      id: "ARTIST_A6_CAREWATCH",
      type: "multi",
      title: "CareWatch",
      quote: "A calm check-in after the appointment reduces anxiety and surfaces issues early — without getting weird.",
      question: "When should Isla check in?",
      key: "carewatch.checkpoints",
      options: [
        { label: "24 hours (recommended)", value: "24h" },
        { label: "5 days (recommended)", value: "5d" },
        { label: "7 days", value: "7d" },
        { label: "Retouch window reminder (5–6 months)", value: "retouch_5_6m" },
        { label: "Never", value: "never" },
      ],
      next: "ARTIST_A7_AFTERCARE_REGIMEN",
    },
    {
      id: "ARTIST_A7_AFTERCARE_REGIMEN",
      type: "single",
      title: "Aftercare",
      quote: "Isla will deliver your aftercare instructions for you — exactly how you prefer.",
      question: "Which aftercare regimen do you recommend most often?",
      key: "aftercare.regimen",
      options: [
        { label: "Mild soap + water, then light unscented lotion", value: "soap_water_lotion" },
        { label: "Antibacterial soap + Aquaphor (thin layer)", value: "antibacterial_aquaphor" },
        { label: "Dial Gold + thin ointment (first days), then lotion", value: "dial_gold_ointment_then_lotion" },
        { label: "Saniderm / second-skin style aftercare", value: "second_skin" },
        { label: "Case-by-case (always ask me)", value: "case_by_case" },
      ],
      next: "ARTIST_A8_PORTFOLIO",
    },
    {
      id: "ARTIST_A8_PORTFOLIO",
      type: "single",
      title: "Portfolio",
      quote: "Only with consent. Always respectful.",
      question:
        "Isla can help you build your online portfolio.\nShe can request photos and posting consent for you.\nWould you like her to help you build your portfolio?",
      key: "media.enabled",
      options: [
        { label: "Yes", value: true, primary: true },
        { label: "No", value: false },
      ],
      next: (state) => (get(state, "media.enabled") ? "ARTIST_A8B_HEALED_PHOTO_TIMING" : "ARTIST_A9_REVIEWS"),
    },
    {
      id: "ARTIST_A8B_HEALED_PHOTO_TIMING",
      type: "single",
      title: "Healed photos",
      quote: "When it’s time, Isla handles the ask — and consent.",
      question: "When should Isla request a healed photo?",
      key: "media.timing_days",
      options: [
        { label: "30 days (recommended)", value: 30, primary: true },
        { label: "45 days", value: 45 },
        { label: "60 days", value: 60 },
      ],
      next: "ARTIST_A9_REVIEWS",
    },
    {
      id: "ARTIST_A9_REVIEWS",
      type: "single",
      title: "Reviews",
      quote: "Only after Isla knows it was a good experience.",
      question: "Should Isla request reviews for you?",
      key: "reviews.enabled",
      options: [
        { label: "Yes — only after good experiences", value: true, primary: true },
        { label: "No", value: false },
      ],
      next: "ARTIST_A10_REINVITE",
    },
    {
      id: "ARTIST_A10_REINVITE",
      type: "multi",
      title: "Invite them back",
      quote: "Isla can help keep your books full by inviting clients back at the right time.",
      question: "When should Isla invite clients back?",
      key: "rebooking.timing",
      exclusive: ["client_initiates", "never"],
      options: [
        { label: "1 month", value: 1 },
        { label: "3 months", value: 3 },
        { label: "6 months (recommended)", value: 6 },
        { label: "9 months", value: 9 },
        { label: "12 months", value: 12 },
        { label: "Only if the client initiates", value: "client_initiates" },
        { label: "Never", value: "never" },
      ],
      next: "ARTIST_END",
    },
    {
      id: "ARTIST_END",
      type: "end",
      title: "",
      quote: "",
      question: "Onboarding complete.\nYour preferences have been sent.",
    },
  ],
};

window.RR_ONBOARDING_FLOWS = FLOWS;